name: flutter_app_template
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  auto_route: ^7.2.0
  bloc: ^8.1.2
  connectivity_plus: ^4.0.1
  dartz: ^0.10.1
  dio: ^5.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  google_fonts: ^4.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
